import Head from 'next/head'
import styles from '@/styles/Home.module.css'

import Layout from '@/components/Layout'
import Joke from '@/components/Joke'
import UserJokes from '@/components/UserJokes'

export default function Home({ jokes, userJokes }) {
  return (
    <>
      <Head>
        <title>Random Joke Generator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css"></link>
      </Head>
      <Layout>
        <Joke jokes={jokes} />
        <UserJokes userJokes={userJokes} />
      </Layout>
    </>
  )
}

export async function getStaticProps() {
  const responses = await Promise.all([
    fetch('https://official-joke-api.appspot.com/random_ten/'),
    fetch(`${process.env.API_URL}/resources`)
  ])

  const data1 = await responses[0].json()
  const data2 = await responses[1].json()

  return {
    props: {
      jokes: data1,
      userJokes: data2,
    },
  }
}
