import Head from 'next/head'

import Layout from '@/components/Layout'
import Form from '@/components/Form'

export default function Submit() {
  return (
    <>
      <Head>
        <title>Random Joke Generator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css"></link>
      </Head>
      <Layout>
        <Form />
      </Layout>
    </>
  )
}